spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456 # ← thay bằng mật khẩu thực tế của bạn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # tạo bảng nếu chưa có, cập nhật nếu có
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  max-borrow-days: 14
  max-books-per-user: 5
